spring:
  application:
    name: spring-ai-rag
#Pass API key as environment variable, e.g. -DOPENAI_API_KEY=your-api-key
  ai:
    ollama:
      embedding:
       options:
         model: deepseek-r1:
sfg:
  aiapp:
    vectorStorePath: /tmp/vectorstore.json
    documentsToLoad:
      - classpath:/movies500Trimmed.csv