spring:
  application:
    name: spring-ai-rag
  ai:
    ollama:
      init:
        pull-model-strategy: when_missing
      chat:
        options:
          model: deepseek-r1:14b
      embedding:
        options:
          model: mxbai-embed-large
sfg:
  aiapp:
    vectorStorePath: /tmp/vectorstore.json
    documentsToLoad:
      - classpath:/cayen-doc.csv