spring:
  application:
    name: spring-ai-rag
  #  ai:
  #    ollama:
  #      init:
  #        pull-model-strategy: when_missing
  #      chat:
  #        options:
  #          model: llama2:13b
  #      embedding:
  #        options:
  #          model: mxbai-embed-large
  ai:
    openai:
      api-key: sk-lycAMKxPhdaQB4O5zKNAJl6glipIhRsR
      base-url: https://api.proxyapi.ru/openai/v1
      chat:
        options:
          model: gpt-3.5-turbo
      embedding:
        base-url: https://api.proxyapi.ru/openai/v1
        options:
          model: text-embedding-ada-002
          dimensions: 1536
sfg:
  aiapp:
    vectorStorePath: /tmp/vectorstore.json
    documentsToLoad:
      - classpath:/prompt.pdf
logging:
  level:
    guru.springframework.springairag.services: debug
    root: INFO