spring:
  application:
    name: spring-ai-rag
#Pass API key as environment variable, e.g. -DOPENAI_API_KEY=your-api-key
  ai:
    ollama:
      init:
        pull-model-strategy: when_missing
      chat:
        options:
          model: mistral
      embedding:
        options:
          model: mistral-embeddings
sfg:
  aiapp:
    vectorStorePath: /tmp/vectorstore.json
    documentsToLoad:
      - classpath:/movies500Trimmed.csv
    promptTemplate: classpath:/templates/rag-prompt-template-meta-ru.st